/**
 * DreamDwell Inspiration Photo Database
 * 60+ unique images across all styles and rooms
 * Zero duplicate image URLs
 */

export const PHOTO_DATABASE = [
  // ═══ MINIMALIST (7) ═══
  {
    id: 'minimalist-living-01',
    title: 'Soft Minimal Lounge',
    style: 'Minimalist',
    room: 'Living Room',
    mood: 'Calm',
    palette: ['#f4efe8', '#d8d0c7', '#8f857b'],
    materials: ['wood', 'linen', 'plaster'],
    tags: ['minimalist', 'calm', 'neutral', 'living room', 'natural light', 'clean lines'],
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=900&q=80',
    description: 'Layered neutrals, pale oak, and soft edges for a quiet everyday space.',
    shopUrl: 'https://www.lazada.com.ph/catalog/?q=minimalist+living+room+decor',
    height: 420,
  },
  {
    id: 'minimalist-bedroom-01',
    title: 'Gallery White Bedroom',
    style: 'Minimalist',
    room: 'Bedroom',
    mood: 'Airy',
    palette: ['#fbfaf7', '#ddd6cf', '#b8ada1'],
    materials: ['cotton', 'wood', 'limewash'],
    tags: ['minimalist', 'airy', 'bedroom', 'white', 'soft bedding', 'serene'],
    imageUrl: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=700&q=80',
    description: 'A light-filled retreat with tonal layers and low visual noise.',
    shopUrl: 'https://www.lazada.com.ph/catalog/?q=minimalist+bedroom+decor',
    height: 520,
  },
  {
    id: 'minimalist-office-01',
    title: 'Focus First Studio',
    style: 'Minimalist',
    room: 'Office',
    mood: 'Focused',
    palette: ['#f3f3f0', '#cfcfc7', '#5b5b57'],
    materials: ['ash wood', 'steel', 'fabric'],
    tags: ['minimalist', 'office', 'workspace', 'focus', 'clean', 'productivity'],
    imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=900&q=80',
    description: 'A crisp workstation that keeps the eye and mind uncluttered.',
    shopUrl: 'https://www.lazada.com.ph/catalog/?q=minimalist+office+desk+setup',
    height: 360,
  },
  {
    id: 'minimalist-kitchen-01',
    title: 'Pure White Kitchen',
    style: 'Minimalist',
    room: 'Kitchen',
    mood: 'Serene',
    palette: ['#ffffff', '#e8e8e8', '#b0b0b0'],
    materials: ['marble', 'steel', 'glass'],
    tags: ['minimalist', 'kitchen', 'white', 'clean', 'bright', 'modern'],
    imageUrl: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=80',
    description: 'A serene culinary space where every element earns its place.',
    shopUrl: 'https://www.lazada.com.ph/catalog/?q=minimalist+kitchen+decor',
    height: 480,
  },
  {
    id: 'minimalist-bath-01',
    title: 'Spa Minimal Bath',
    style: 'Minimalist',
    room: 'Bathroom',
    mood: 'Tranquil',
    palette: ['#f5f5f0', '#d4d4d0', '#8a8a85'],
    materials: ['stone', 'ceramic', 'wood'],
    tags: ['minimalist', 'bathroom', 'spa', 'tranquil', 'stone', 'clean'],
    imageUrl: 'https://images.unsplash.com/photo-1620626012053-1c1e0f5d2b3c?auto=format&fit=crop&w=900&q=80',
    description: 'Quiet stone and soft light for a restorative bathing ritual.',
    shopUrl: 'https://www.lazada.com.ph/catalog/?q=minimalist+bathroom+decor',
    height: 550,
  },
  {
    id: 'minimalist-dining-01',
    title: 'Mono Dining Space',
    style: 'Minimalist',
    room: 'Dining Room',
    mood: 'Refined',
    palette: ['#f0f0ec', '#c5c5c0', '#3a3a3a'],
    materials: ['wood', 'linen', 'metal'],
    tags: ['minimalist', 'dining', 'refined', 'monochrome', 'wood table'],
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80',
    description: 'A dining space of quiet confidence and considered restraint.',
    shopUrl: 'https://www.lazada.com.ph/catalog/?q=minimalist+dining+room',
    height: 460,
  },
  {
    id: 'minimalist-entry-01',
    title: 'Calm Entry Hall',
    style: 'Minimalist',
    room: 'Entryway',
    mood: 'Welcoming',
    palette: ['#f8f8f4', '#dcd8d0', '#7a756d'],
    materials: ['wood', 'stone', 'metal'],
    tags: ['minimalist', 'entryway', 'welcoming', 'calm', 'simple'],
    imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80',
    description: 'An understated arrival that whispers rather than shouts.',
    shopUrl: 'https://www.lazada.com.ph/catalog/?q=minimalist+entryway',
    height: 500,
  },

  // ═══ SCANDINAVIAN (7) ═══
  {
    id: 'scandi-living-01',
    title: 'Warm Scandinavian Nest',
    style: 'Scandinavian',
    room: 'Living Room',
    mood: 'Cozy',
    palette: ['#f7f3ec', '#d9ccb6', '#7c6753'],
    materials: ['oak', 'boucle', 'wool'],
    tags: ['scandinavian', 'cozy', 'living room', 'light wood', 'texture', 'warm'],
    imageUrl: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=900&q=80',
    description: 'Cream textiles, pale timber, and practical comfort in balance.',
    shopUrl: 'https://www.lazada.com.ph/catalog/?q=scandinavian+living+room+decor',
    height: 500,
  },
  {
    id: 'scandi-kitchen-01',
    title: 'Oak + White Kitchen',
    style: 'Scandinavian',
    room: 'Kitchen',
    mood: 'Fresh',
    palette: ['#fcfbf8', '#d7c9b7', '#8c7862'],
    materials: ['oak', 'stone', 'ceramic'],
    tags: ['scandinavian', 'kitchen', 'bright', 'oak', 'storage', 'fresh'],
    imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=900&q=80',
    description: 'A clean, bright kitchen grounded with warm timber cabinetry.',
    shopUrl: 'https://www.lazada.com.ph/catalog/?q=scandinavian+kitchen+decor',
    height: 420,
  },
  {
    id: 'scandi-bedroom-01',
    title: 'Cloud Linen Bedroom',
    style: 'Scandinavian',
    room: 'Bedroom',
    mood: 'Restful',
    palette: ['#f8f6f2', '#dbd1c5', '#6d6258'],
    materials: ['linen', 'oak', 'paper'],
    tags: ['scandinavian', 'bedroom', 'linen', 'light', 'restful', 'simplicity'],
    imageUrl: 'https://images.unsplash.com/photo-1505693416388-c5402a4d0d24?auto=format&fit=crop&w=900&q=80',
    description: 'Light oak, matte whites, and gentle texture for better rest.',
    shopUrl: 'https://www.lazada.com.ph/catalog/?q=scandinavian+bedroom+decor',
    height: 560,
  },
  {
    id: 'scandi-office-01',
    title: 'Nordic Work Nook',
    style: 'Scandinavian',
    room: 'Office',
    mood: 'Bright',
    palette: ['#f5f2ec', '#d4cdc0', '#5e574e'],
    materials: ['birch', 'wool', 'brass'],
    tags: ['scandinavian', 'office', 'bright', 'birch', 'clean', 'workspace'],
    imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=900&q=80',
    description: 'A sunlit workspace with pale wood and quiet order.',
    shopUrl: 'https://www.lazada.com.ph/catalog/?q=scandinavian+office+decor',
    height: 440,
  },
  {
    id: 'scandi-bath-01',
    title: 'Hygge Bath Retreat',
    style: 'Scandinavian',
    room: 'Bathroom',
    mood: 'Warm',
    palette: ['#f4f0e8', '#cfc5b4', '#6b6255'],
    materials: ['wood', 'stone', 'textile'],
    tags: ['scandinavian', 'bathroom', 'hygge', 'warm', 'wood accents', 'spa'],
    imageUrl: 'https://images.unsplash.com/photo-1584622050111-993a426fbf0a?auto=format&fit=crop&w=900&q=80',
    description: 'Wood-accented warmth meets clean Nordic practicality.',
    shopUrl: 'https://www.lazada.com.ph/catalog/?q=scandinavian+bathroom',
    height: 580,
  },
  {
    id: 'scandi-living-02',
    title: 'Nordic Light Living',
    style: 'Scandinavian',
    room: 'Living Room',
    mood: 'Airy',
    palette: ['#faf8f4', '#e2dbd0', '#8a8076'],
    materials: ['pine', 'wool', 'linen'],
    tags: ['scandinavian', 'living room', 'airy', 'light', 'bright', 'white walls'],
    imageUrl: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=900&q=80',
    description: 'Flooded with natural light, softened by wool and pale timber.',
    shopUrl: 'https://www.lazada.com.ph/catalog/?q=nordic+living+room',
    height: 470,
  },
  {
    id: 'scandi-dining-01',
    title: 'Nordic Gather Table',
    style: 'Scandinavian',
    room: 'Dining Room',
    mood: 'Inviting',
    palette: ['#f5f0e6', '#d8cdb8', '#6e6355'],
    materials: ['oak', 'linen', 'ceramic'],
    tags: ['scandinavian', 'dining', 'inviting', 'oak table', 'linen', 'gathering'],
    imageUrl: 'https://images.unsplash.com/photo-1600566753086-00f18c169577?auto=format&fit=crop&w=900&q=80',
    description: 'A warm oak table surrounded by linen chairs for Nordic gatherings.',
    shopUrl: 'https://www.lazada.com.ph/catalog/?q=nordic+dining+table',
    height: 450,
  },
];
